apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvmicro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvmicro
  template:
    metadata:
      labels:
        app: nvmicro
    spec:
      containers:
      - name: nvmicro
        image: uberman42/nvmicro:v0.8.3
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
      - name: prometheus-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.5.0
        command: ["/monitor"]
        args:
        - --source=:http://localhost:5000
        - --stackdriver-prefix=custom.googleapis.com
        - --pod-id=$(POD_ID)
        - --namespace-id=$(POD_NAMESPACE)
        resources:
          requests:
            cpu: 50m
        env:
        # save Kubernetes metadata as environment variables for use in metrics
        - name: POD_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace