apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-nvmicro
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nvmicro
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - pods:
      metric:
        name: custom.googleapis.com|requests_since_last
        selector: {}
      target:
        averageValue: "60"
        type: AverageValue
    type: Pods
  