apiVersion: v1
kind: Service
metadata:
  name: nvmicro
  labels:
    app: nvmicro
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: nvmicro
  type: LoadBalancer
  