apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-nvmicro
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: nvmicro
  updatePolicy:
    updateMode: "Auto"